# Generated by Django 2.0.7 on 2018-07-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180731_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True, help_text='Image url', null=True),
        ),
    ]
